Deploy cookbooks
wazuh/wazuh-chef pull request #115
Opened 2020-11-27 14:14 UTC by sergiogp98

This PR try to deploy different cookbooks depending on the installation type:

- With opendistro:

- [ ] opendistro.rb

- [ ] filebeat-oss.rb

- With elastic:

- [ ] elastic-stack.rb

- [ ] filebeat.rb

Also the two wazuh cookbooks:

- [ ] wazuh-manager

- [ ] wazuh-agent

2020-12-28 16:35 UTC, Zenidd requested changes
Please, check the comments @sergiogp98.

_- JP_

2020-12-28 16:35 UTC, Zenidd commented on README.md
> +cookbook "wazuh_server", git: "https://github.com/wazuh/wazuh-chef.git", rel: 'cookbooks/wazuh_manager'
Why using `git` in some lines and `github` in others ?

2020-12-28 16:35 UTC, Zenidd commented on README.md
>  Each cookbook has its README.md
Could we remove this line and link each cookbook line with its README.md file?

2020-12-28 16:35 UTC, Zenidd commented on cookbooks/README.md
> +These cookbooks don't configure Windows systems yet. For manual agent installation on Windows, check the [documentation](https://documentation.wazuh.com/4.0/installation-guide/wazuh-agent/wazuh_agent
Please, use `current` as it will always point to the latest release documentation.

2020-12-28 16:35 UTC, Zenidd commented on cookbooks/README.md
> +For example: To enable cluster configuration, the following line would be changed in ```/cookbooks/wazuh_manager/attributes/cluster.rb ``` file:
would be `replaced`

2020-12-28 16:35 UTC, Zenidd commented on cookbooks/README.md
> +You can configure your Wazuh [Centralized Configuration](https://documentation.wazuh.com/4.0/user-manual/reference/centralized-configuration.html#centralized-configuration-process) with Chef.
You can `set up` you Wazuh..

2020-12-28 16:35 UTC, Zenidd commented on cookbooks/elastic-stack/README.md
> +2. `['elastic']['yml']['cluster']['initial_master_nodes']`: Allows to insert the whole line for the initial master nodes. You can declare it like:
`You can declare it like` --> `Usage example`

2020-12-28 16:35 UTC, Zenidd commented on cookbooks/elastic-stack/README.md
> +One example of the previously stated configuration would be the following.
the following:

2020-12-28 16:35 UTC, Zenidd commented on cookbooks/elastic-stack/README.md
> +If only the declaration of `cluster.initial_master_nodes` to *192.168.0.1* would be wanted, the Elastic role needs to be adapted like this:
The hereunder example shows a simple override attribute example on Elastic role:

2020-12-28 16:35 UTC, Zenidd commented on cookbooks/elastic-stack/recipes/default.rb
> +# include_recipe 'wazuh_manager::default'
Should we remove these recipes or include them?

2020-12-28 16:35 UTC, Zenidd commented on cookbooks/README.md
> +These cookbooks don't configure Windows systems yet. For manual agent installation on Windows, check the [documentation](https://documentation.wazuh.com/4.0/installation-guide/wazuh-agent/wazuh_agent
Please, use current instead of fixed version

2020-12-28 16:35 UTC, Zenidd commented on cookbooks/filebeat/README.md
> +Check [Filebeat installation documentation](https://documentation.wazuh.com/4.0/learning-wazuh/build-lab/install-wazuh-manager.html#install-filebeat) for more detail
Please, use current instead of fixed version

2020-12-28 16:35 UTC, Zenidd commented on README.md
> +Since Wazuh 4.0, by default, the agent registers automatically with the manager through enrollment. Configuration details can be found on [Enrollment section](https://documentation.wazuh.com/4.0/user
Please, use current instead of fixed version

2020-12-28 16:35 UTC, Zenidd commented on cookbooks/README.md
> +You can configure your Wazuh [Centralized Configuration](https://documentation.wazuh.com/4.0/user-manual/reference/centralized-configuration.html#centralized-configuration-process) with Chef.
You can set up you Wazuh...

Also, please, consider using current instead of fixed version

2020-12-28 16:35 UTC, Zenidd commented on cookbooks/elastic-stack/README.md
> +If only the declaration of `cluster.initial_master_nodes` to *192.168.0.1* would be wanted, the Elastic role needs to be adapted like this:
The hereunder example shows a simple configuration override for `initial_master_nodes` variable

2020-12-28 16:35 UTC, Zenidd commented on README.md
>  There is software that must be installed to ensure the correct installation.
Dependencies missing here

2020-12-28 16:35 UTC, Zenidd commented on README.md
> +all the software products they have.
`to know all the software products they have.` --> `for further information`

2020-12-28 16:35 UTC, Zenidd commented on cookbooks/README.md
> +For example: To enable cluster configuration, the following line would be changed in ```/cookbooks/wazuh_manager/attributes/cluster.rb ``` file:
the following line would be replaced in

2020-12-28 16:35 UTC, Zenidd commented on cookbooks/elastic-stack/recipes/default.rb
> +# include_recipe 'wazuh_manager::default'
Should the manager be installed in this default recipe? In other case, should we remove it?

2020-12-28 16:35 UTC, Zenidd commented on cookbooks/filebeat-oss/test/integration/filebeat-oss/filebeat-oss_test.rb
> +    it { should be_installed }
I think we must check here if package is running and enabled:

```
should be_running
should be_enabled
```

2020-12-28 16:35 UTC, Zenidd commented on cookbooks/wazuh_agent/test/integration/wazuh_agent/agent_test.rb
> +describe service('wazuh-agent') do
I think we must check here service is enabled

2020-12-28 16:35 UTC, Zenidd commented on cookbooks/filebeat/test/integration/filebeat/filebeat_test.rb
> +    it { should be_running }
I think we should check if service in enabled

2020-12-28 16:35 UTC, Zenidd commented on cookbooks/opendistro/test/integration/opendistro/elasticsearch_test.rb
> +  it { should be_running }
I think we should check if service is enabled

2020-12-28 16:40 UTC, sergiogp98 commented on README.md
> +cookbook "wazuh_server", git: "https://github.com/wazuh/wazuh-chef.git", rel: 'cookbooks/wazuh_manager'
Thanks for the advise, with _git_ the repository should be referenced with the entire URL mainwhile with _github_ only owner/repository

2020-12-28 17:12 UTC, sergiogp98 commented on cookbooks/README.md
> +You can configure your Wazuh [Centralized Configuration](https://documentation.wazuh.com/4.0/user-manual/reference/centralized-configuration.html#centralized-configuration-process) with Chef.
What do you mean?

2021-01-04 10:55 UTC, Zenidd commented on README.md
> +Since Wazuh 4.0, by default, the agent registers automatically with the manager through enrollment. Configuration details can be found on [Enrollment section](https://documentation.wazuh.com/current/
`the agent registers automatically with the manager through enrollment` --> `the automatically registers against the manager`

2021-01-04 11:01 UTC, Zenidd commented on cookbooks/elastic-stack/README.md
> +* ``yml.rb``: customize YAML configuration file for Elasticsearch and Kibana services
Please, replace `yml.rb` with the full filename: `elasticsearch.yml.rb`

2021-01-04 11:11 UTC, Zenidd commented on cookbooks/wazuh_agent/README.md
> +Agent is automatically registered in the specified address by using ['agent authd'](https://documentation.wazuh.com/current/user-manual/agents/registering-agents/register-agent-authd.html#simple-meth
Currently, the agent is automatically registered using enrollment. Please, update the reference.

2021-01-05 10:57 UTC, Zenidd approved these changes
LGTM. Great work @sergiogp98.

_-JP_

2021-01-05 10:58 UTC, merged